### ISSUE TITLE
Exception when unable to resolve hostname

### ISSUE THREAD

**Issue by ajwhite** [tradle/react-native-udp#14]
I hit this when doing some physical device testing (actual hostname omtited, but it's a valid hostname)

```
E/AndroidRuntime( 1086): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime( 1086): 	at android.os.AsyncTask$3.done(AsyncTask.java:304)
E/AndroidRuntime( 1086): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime( 1086): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime( 1086): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime( 1086): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime( 1086): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 1086): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 1086): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime( 1086): Caused by: java.lang.IllegalArgumentException: Socket address unresolved: XXX.XXXXXX.com:12345
E/AndroidRuntime( 1086): 	at java.net.DatagramPacket.setSocketAddress(DatagramPacket.java:315)
E/AndroidRuntime( 1086): 	at java.net.DatagramPacket.<init>(DatagramPacket.java:266)
E/AndroidRuntime( 1086): 	at com.tradle.react.UdpSenderTask.doInBackground(UdpSenderTask.java:38)
E/AndroidRuntime( 1086): 	at com.tradle.react.UdpSenderTask.doInBackground(UdpSenderTask.java:21)
E/AndroidRuntime( 1086): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/AndroidRuntime( 1086): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime( 1086): 	... 4 more
```

**Comment by aprock** [comment]
odd, the InetSocketAddress should be resolving.

**Comment by ajwhite** [comment]
This may happen during connectivity issues, this has worked 90% of the time for me.

**Comment by aprock** [comment]
@ajwhite does your javascript call to send have a callback? Is it firing with an error?

**Comment by ajwhite** [comment]
It doesn't have a CB, no
